/* Timing. Beat times come from the voiceover: voiceover/timings.json is generated by
   scripts/yt/vo-build.py from the VO takes (word-level alignment + assembly.json, which holds the
   lead-in, the silences after beats and the silent beats). Scenes read beat times, never seconds,
   so re-running the build moves the picture with the voice. */
import { SCRIPT_BEATS } from './script';
import timings from '../../../../youtube/02_videos/2026-W41_redirect-domain/voiceover/timings.json';

export type Timed = {
    n: number; at: number; dur: number; end: number; vo: string;
    /** First and last spoken word, absolute seconds (null for a silent beat). */
    voStart: number | null; voEnd: number | null;
    words: readonly { w: string; s: number; e: number }[];
};

/** Beats with absolute start/end, in seconds. */
export const BEATS: readonly Timed[] = timings.beats.map((b, i) => {
    const vo = SCRIPT_BEATS[i]?.vo ?? '';
    if (SCRIPT_BEATS[i]?.n !== b.n) throw new Error(`timings.json beat ${b.n} does not match script beat ${SCRIPT_BEATS[i]?.n}; re-run scripts/yt/vo-build.py`);
    return { n: b.n, at: b.at, dur: b.end - b.at, end: b.end, vo, voStart: b.voStart, voEnd: b.voEnd, words: b.words };
});

/** Film length in whole seconds (the end card runs to the last frame). music.json must say the same. */
export const TOTAL = Math.ceil(BEATS[BEATS.length - 1].end);

/** Start time of beat n (absolute). */
export const at = (n: number) => BEATS[n - 1].at;
export const end = (n: number) => BEATS[n - 1].end;
/** Absolute start of the first word of beat n that matches `w` (case and punctuation ignored).
    Lets a visual land on the spoken word instead of a guessed offset. Throws if the word is not in the beat. */
export function word(n: number, w: string): number {
    const key = w.toLowerCase().replace(/[^a-z0-9']/g, '');
    const hit = BEATS[n - 1].words.find((x) => x.w.toLowerCase().replace(/[^a-z0-9']/g, '') === key);
    if (!hit) throw new Error(`beat ${n} has no word "${w}"`);
    return hit.s;
}

/** Scene windows: [first beat, last beat]. Scenes overlap by `lap` seconds so transitions can carry both. */
export const SCENES = {
    hook: [1, 10],
    ideas: [11, 24],
    walkthrough: [25, 36],
    test: [37, 47],
    close: [48, 52],
    end: [53, 53],
} as const;
export type SceneKey = keyof typeof SCENES;

export function sceneWindow(key: SceneKey, lap = 0.4): readonly [number, number] {
    const [a, b] = SCENES[key];
    // The end card runs to the last frame so the film never ends on black.
    return [Math.max(0, at(a) - (key === 'hook' ? 0 : lap)), key === 'end' ? TOTAL : Math.min(TOTAL, end(b))];
}

/** Local time helpers for a scene: beat start/end relative to the scene's start. */
export function local(key: SceneKey) {
    const [s] = sceneWindow(key);
    return { at: (n: number) => at(n) - s, end: (n: number) => end(n) - s, word: (n: number, w: string) => word(n, w) - s, start: s };
}
