/* The reel's background beat: public/audio/<composition id>-beat.mp3, generated by
   `npm run audio` from src/remotion/reels/<id>/music.json (scripts/audio/beat.py).
   Sound effects go on top with <Sfx>, tied to on-screen events. The beat is
   drums only and normalized to -16 LUFS with headroom, so it plays at full volume. */
import { Html5Audio, staticFile, useVideoConfig } from 'remotion';

export function Beat({ volume = 1 }: { volume?: number }) {
    const { id } = useVideoConfig();
    return <Html5Audio src={staticFile(`audio/${id}-beat.mp3`)} volume={volume} />;
}
