/* The reel's background beat: public/audio/<composition id>-beat.mp3, generated by
   `npm run audio` from src/remotion/reels/<id>/music.json (scripts/audio/beat.py).
   Sound effects go on top with <Sfx>, tied to on-screen events. Default volume
   0.85 leaves headroom so beat + SFX peaks stay under -1 dBFS. */
import { Html5Audio, staticFile, useVideoConfig } from 'remotion';

export function Beat({ volume = 0.85 }: { volume?: number }) {
    const { id } = useVideoConfig();
    return <Html5Audio src={staticFile(`audio/${id}-beat.mp3`)} volume={volume} />;
}
