/* Sound effects from public/audio/sfx (generated by scripts/audio/generate.py). */
import { Html5Audio, Sequence, staticFile, useVideoConfig } from 'remotion';
import manifest from '../../../public/audio/sfx/manifest.json';

/** Length of each effect in seconds, written by scripts/audio/generate.py. Each
    effect is mounted only while it plays, so the browser Player keeps a handful of
    audio elements instead of dozens, which keeps seeking and scrubbing smooth. */
export const SFX_SECONDS = manifest;

export type SfxName = keyof typeof SFX_SECONDS;

/** Restraint is the style: one effect per story beat, none for UI micro-actions.
    At most this many cues per 30 seconds of video (e.g. 6 in a 30s reel). */
export const MAX_SFX_PER_30S = 6;
/** [start (s), effect, volume 0–1] */
export type SfxCue = readonly [number, SfxName, number];

/** A reel whose brief explicitly calls for more effects (e.g. a sound-designed short with
    a repeated click motif) can raise the cap. Say why: the reason is the review trail. */
export type SfxBudget = { max: number; reason: string };

export function Sfx({ cues, budget: override }: { cues: readonly SfxCue[]; budget?: SfxBudget }) {
    const { fps, durationInFrames } = useVideoConfig();
    if (override && !override.reason.trim()) throw new Error('<Sfx budget> needs a reason.');
    const budget = override?.max ?? Math.max(1, Math.floor((durationInFrames / fps / 30) * MAX_SFX_PER_30S));
    if (cues.length > budget) {
        throw new Error(
            `${cues.length} sound effects is too many (max ${budget} for this length). Keep one per story beat ` +
            '(problem, detection, fix, cut to result, end card) and drop UI sounds like clicks and typing. See docs/reel-playbook.md.',
        );
    }
    return (
        <>
            {cues.map(([at, name, volume], i) => (
                <Sequence
                    key={i}
                    name={`sfx: ${name}`}
                    from={Math.round(at * fps)}
                    durationInFrames={Math.max(1, Math.ceil(SFX_SECONDS[name] * fps))}
                    layout="none"
                >
                    <Html5Audio src={staticFile(`audio/sfx/${name}.wav`)} volume={volume} />
                </Sequence>
            ))}
        </>
    );
}
