/* Sound effects from public/audio/sfx (generated by scripts/audio/generate.py). */
import { Html5Audio, Sequence, staticFile, useVideoConfig } from 'remotion';

/** Length of each file in seconds. Each effect is mounted only while it plays,
    so the browser Player keeps a handful of audio elements instead of dozens,
    which keeps seeking and scrubbing smooth. Update when the generator changes. */
export const SFX_SECONDS = {
    impact: 1.8,
    whoosh: 0.7,
    riser: 1.0,
    click: 0.06,
    key: 0.05,
    typing: 1.65,
    alert: 0.9,
    success: 1.3,
    stinger: 3.0,
} as const;

export type SfxName = keyof typeof SFX_SECONDS;
/** [start (s), effect, volume 0–1] */
export type SfxCue = readonly [number, SfxName, number];

export function Sfx({ cues }: { cues: readonly SfxCue[] }) {
    const { fps } = useVideoConfig();
    return (
        <>
            {cues.map(([at, name, volume], i) => (
                <Sequence
                    key={i}
                    name={`sfx: ${name}`}
                    from={Math.round(at * fps)}
                    durationInFrames={Math.max(1, Math.ceil(SFX_SECONDS[name] * fps))}
                    layout="none"
                >
                    <Html5Audio src={staticFile(`audio/sfx/${name}.wav`)} volume={volume} />
                </Sequence>
            ))}
        </>
    );
}
